{
    'name': 'Odoo WooCommerce Connector',
    'version': '12.0.1.1',
    'license': 'OPL-1',
    'category': 'Sale',
    'summary': 'Manage your WooCommerce Stores from Odoo',
    'author': 'Egregious Solutions',
    'website': 'https://egregioussolutions.com/',
    'maintainer': 'Egregious Solutions',
    'depends': ['delivery', 'sale_management', 'sale_stock', 'account', 'stock', 'stock_account'],
    'data': ['security/group.xml',
             'views/stock_inventory.xml',
             'views/view_dashboard.xml',
             'views/view_wc_instance.xml',
             'views/view_wc_template_view.xml',
             'views/view_wc_attribute_term.xml',
             'views/view_wc_attribute_view.xml',
             'views/view_wc_product_images.xml',
             'views/view_wc_variant.xml',
             'views/view_res_partner.xml',
             'views/view_sale_order.xml',
             'views/view_wc_order_status.xml',
             'views/view_stock_picking.xml',
             'views/view_wc_tags.xml',
             'views/view_wc_coupons_view.xml',
             'views/view_wc_product_category.xml',
             'views/view_account_invoice.xml',
             'views/view_wc_process_job.xml',
             'views/view_wc_payment_gateway.xml',
             'wizard/wc_process_import_export_view.xml',
             'wizard/wc_cancel_order_wizard_view.xml',
             'report/report_sale_order.xml',
             'security/ir.model.access.csv',
             'views/ir_cron.xml',
             ],
    'qweb': ['static/src/xml/wc_dashboard.xml'],
    'support':'info@egregioussolutions.com',
    'installable': True,
    'auto_install': False,
    'application': True,
    'price': 199.00,
    'currency': 'EUR',
    'images': ['static/description/banner.png'],
}
